swagger: '2.0'
info:
  title: Maily Herald API
  description: Access Maily Herald data via API.
  version: 1.0.0
host: mailyherald.org
schemes:
  - http
basePath: /api/v1
produces:
  - application/json
